### ISSUE TITLE
Create a production branch

### ISSUE THREAD

**Issue by alvarocavalcanti** [thoughtworks/dashy#15]
This branch shall be used to trigger deploys via Snap. The daily development will be made on the master branch, tho.

**Comment by alvarocavalcanti** [comment]
As discussed with @alabeduarte yesterday, this doesn't make sense. The branch-based CI will be made via Snap watching the master branch. Our deploy will consist only of updating the version via npm command.

So, is it ok to close this?

**Comment by mosampaio** [comment]
To me, it's ok!

So, I'll create a issue to automate the deploy/publish process using the snap-ci.
