### ISSUE TITLE
Create an NPM package for Dashy

### ISSUE THREAD

**Issue by alvarocavalcanti** [thoughtworks/dashy#6]
Dashy needs to be available via NPM in order to provide a simple way to install and run the application (instead of cloning the repo).

**Comment by alabeduarte** [comment]
Available at: https://www.npmjs.org/package/dashy

**Comment by mosampaio** [comment]
It's not working properly. Now it is working only if we input 'dashy start' inside the dashy directory.

**Comment by mosampaio** [comment]
I'm pairing with @alabeduarte to resolve this issue.
